### ISSUE TITLE
你好  你的http_body_parse可以正常运行吗

### ISSUE THREAD

**Issue by wangfpp** [txs1992/toy-browser#1]
我写的在计算chunk包的长度的时候一直没算对过,winter写的是
```
this.length *= 10;
this.length += char.charCodeAt(0)-"0".charCodeAt(0);

// 你写的是
this.length *= 16
this.length += parseInt(char, 16) 
```
以上两种我都试过 都不对呢
![image](https://user-images.githubusercontent.com/35289556/118496924-2b371500-b757-11eb-9e24-8b848509f1b3.png)
数据传输完了还有144个字节呢

**Comment by wangfpp** [comment]
我参考这个人的代码是可以正常运行的
[toy_brow](https://github.com/wangfpp/Frontend-01-Template/blob/master/week05/http-toy/parser.js)

**Comment by txs1992** [comment]
@wangfpp   可以运行的，你可以 clone 到本地运行。

**Comment by wangfpp** [comment]
我直接copy你的代码是不可以的[流泪]

**Comment by wangfpp** [comment]
我感觉是chunk包里面的字符又可能是单字节字符和双字节字符的问题
[这个人的代码好使](https://github.com/wangfpp/Frontend-01-Template/blob/master/week05/http-toy/parser.js#L128)
但是没有明白为啥要用this.length -= 3

**Comment by txs1992** [comment]
@wangfpp  这一段匹配的是中文，中文占 4  个字节，我这里没使用中文，所以没问题

**Comment by wangfpp** [comment]
恩  感谢你的回复:)

**Comment by txs1992** [comment]
@wangfpp 




```ts
/[^\x00-\xff]/.test(char)
``` 
这一段正则匹配的是中文，中文占 4  个字节，我这里没使用中文，所以没问题
